const QUERIES = {
  User: "user",
  USERS_LIST: "users-list",
  languageList: "languageList",
  countryDDL: "countryDDL",
  airlineList: "airlinelist",
  airportList: "airportlist",
  areaList: "areaList",
  cityList: "cityList",
  zoneList: "zoneList",
  policyList: "policyList",
  currencyList: "currencyList",
  AgentGroupList: "AgentGroupList",
  BranchList: "BranchList",
  AgentList: "AgentList",
  AgentCreditLimit: "AgentCreditLimit",
  AgentCardDetails: "AgentCardDetails",
  AgentPayment: "AgentPayment",
  AgentPaymentGateway: "AgentPaymentGateway",
  AgentRegistration: "AgentRegistration",
  AgentSMTP: "AgentSMTP",
  AgentDiscountPayment: "AgentDiscountPayment",
  AgentListBasedOnGroup: "AgentListBasedOnGroup",
  AgentSourceAssociationList: "AgentSourceAssociationList",
  countrylist: "countrylist",
  BuyRuleList: "buyRuleList",
  MarketList: "MarketList",
  RoomCategoryList: "RoomCategoryList",
  HotelCategoryList: "HotelCategoryList",
  SupplementList: "SupplementList",
  HotelFacilityList: "HotelFacilityList",
  MealPlanList: "MealPlanList",

  AutoChargeList: "AutoChargeList",
  StaffList: "StaffList",

  SellRulesList: "SellRulesList",
  PaymentCashSettingList: "PaymentCashSettingList",
  CardChargeList: "CardChargeList",
  PaymentGatewayList: "PaymentGatewayList",
  sourceList: "sourceList",
  sourceBlackoutList: "sourceBlackoutList",
  SupplierBlackoutList: "SupplierBlackoutList",
  sourceAirLineBlackoutList: "sourceAirLineBlackoutList",
  manageSectorBlackoutList: "manageSectorBlackoutList",
  SuppliersList: "SuppliersList",
  SupplierBankDetailssList: "SupplierBankDetailssList",
  SupplierHotelBlackoutList: "SupplierHotelBlackoutList",

  HotelInfosList: "HotelInfosList",
  HotelOfferFreeNightsList: "HotelOfferFreeNightsList",
  HotelOfferLongStaysList: "HotelOfferLongStaysList",
  HotelOfferUpgradesList: "HotelOfferUpgradesList",
  HotelOfferOthersList: "HotelOfferOthersList",
  HotelSuppliersList: "HotelSuppliersList",
  HotelSeasonMasterList: "HotelSeasonMasterList",
  HotelSupplierRoomCategoryFacility: "HotelSupplierRoomCategoryFacility",
  HotelSupplierRoomsList: "HotelSupplierRoomsList",
  HotelSupplierFactSheetsList: "HotelSupplierFactSheetsList",
  HotelRateList: "HotelRateList",
  HotelSupplementChargesList: "HotelSupplementChargesList",
  HotelRestrictDaysList: "HotelRestrictDaysList",
  HotelAgeRangesList: "HotelAgeRangesList",
  HotelStayLimitList: "HotelStayLimitList",
  HotelOfferOtherList: "HotelOfferOtherList",
  HotelOfferUpgradeList: "HotelOfferUpgradeList",
  HotelOfferPromotionalRatesList: "HotelOfferPromotionalRatesList",
  HotelOfferPackageRatesList: "HotelOfferPackageRatesList",
  RoomFacilityList: "RoomFacilityList",

  AllocationsList: "AllocationsList",
  HotelOfferEarlyBirdsList: "HotelOfferEarlyBirdsList",
  HotelSupplierAllocationAgentsList: "HotelSupplierAllocationAgentsList",
  HotelSupplierAllocationPerDaysList: "HotelSupplierAllocationPerDaysList",

  //charter
  AircraftList: "AircraftList",
  AircraftClassList: "AircraftClassList",
  CharterAirLine: "CharterAirLine",
  AircraftSchedule: "AircraftSchedule",
  DailyFlightList: "DailyFlightList",
  DailyFlightDetails: "DailyFlightDetails",
  BlockSeatsList: "BlockSeatsList",
  CharterFaresList: "CharterFaresList",
  PushSeatsDailyFlight: "PushSeatsDailyFlight",
  AncillaryList: "AncillaryList",
  SeatMapAllotment: "SeatMapAllotment",
  CharterBundlesList: "CharterBundlesList",

  // vehicle
  VehicleCategoryList: "VehicleCategoryList",
  VehicleList: "VehicleList",
  VehicleHotelList: "VehicleHotelList",
  VehicleSupplierList: "VehicleSupplierList",
  VehicleSupplierRateList: "VehicleSupplierRateList",
  VehicleTransferInfoList: "VehicleTransferInfoList",
  // Sight Seeing
  SightSeeingCategoryList: "SightSeeingCategoryList",
  SightSeeingSupplierList: "SightSeeingSupplierList",
  SightSeeingTourList: "SightSeeingTourList",
  SightSeeingTourRateList: "SightSeeingTourRateList",
  HotelSupplierAvailabilitiyList: "HotelSupplierAvailabilitiyList",
  //Booking
  FlightData: "FlightsData",
  BookingList: "BookingList",
  FlightDetails: "FlightDetails",
  HotelData: "HotelData",
  TransferData:"TransferData",
  SightseeingData: "SightseeingData",

  // ===========
  ClubList: "ClubList"
};
const PAGINATION_PAGES_COUNT = 3;
const defaultPageNumberInPagination = 1;
const defaultPageSizeInPagination = 10;

export {
  QUERIES,
  PAGINATION_PAGES_COUNT,
  defaultPageNumberInPagination,
  defaultPageSizeInPagination,
};
