export enum PermissionsEnum {
  "Access Super Club" = 1,
  "Access Super Courts" = 2,
  "Access Super Genderal" = 4,
  "Access Super Reservtion" = 8,
  "Access Admin Control" = 16,
  "Access Super Delete" = 32,
  "Access Super Edit" = 64,
  "Access Super Create" = 128,
  "Access Club Reservation" = 256,
  "Access Club Courts" = 512,
  // "Access Club Users" = 1024,
  "Access Club Slot/Delete" = 2048,
  "Access Club Slot/Edit" = 4096,
  "Access Club Slot/Create" = 8192,
  "Access Club Schedule/Delete" = 16384,
  "Access Club Schedule/Edit" = 32768,
  "Access Club Schedule/Create" = 65536,
}